//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TestClientSrc.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FORMVIEW_BURN               101
#define IDD_TESTCLIENTSRC_DIALOG        102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_FORMVIEW_PRINT              103
#define IDD_FORMVIEW_TRANSFER           104
#define IDD_FORMVIEW                    105
#define IDD_FORMVIEW_WLMPPS             105
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_BURN_INFO            134
#define IDD_FORMVIEW_IMPORT             135
#define IDI_ICON_TOP                    135
#define IDD_FORMVIEW_DCM_READ           136
#define IDI_ICON_UNTOP                  136
#define IDD_FORMVIEW_DISC_IMPORT        137
#define IDI_ICON_EXIT_SD_PA             137
#define IDI_ICON_EXIT_UNSHUTDOWN_PA     137
#define IDI_ICON_DESKTOP                138
#define IDD_FORMVIEW_PAGENERAL          138
#define IDI_ICON_DESKTOP_2              139
#define IDD_FORMVIEW_PATIENTADMIN       139
#define IDD_FORMVIEW_SERIES_IMAGE       140
#define IDD_FORMVIEW_IMAGE              141
#define IDD_FORMVIEW_CONFIG             142
#define IDD_FORMVIEW_SERVER             143
#define IDD_FORMVIEW_IMPORT_JOB_DETAIL  144
#define IDD_FORMVIEW_SEND_JOB_DETAIL    145
#define IDD_FORMVIEW_BURN_JOB_DETAIL    146
#define IDI_ICON_EXIT_SHUTDOWN_PA       147
#define IDB_BITMAP_STATE                149
#define IDR_TRAYICON                    150
#define IDB_BITMAP_SD_PA                153
#define IDB_BITMAP_UNSD_PA              154
#define IDI_ICON_XP_SDPA                155
#define IDI_ICON_XP_UNSDPA              156
#define IDB_BITMAP_XP_UNSDPA            159
#define IDB_BITMAP_XP_SDPA              160
#define IDI_ICON_XP_DESKTOP             162
#define IDB_BITMAP_DESKTOP              163
#define IDR_MENU_TEST                   166
#define IDI_ICON_MAKE_PAREG             168
#define IDR_TOOLBAR                     169
#define IDC_PRINT                       1000
#define IDC_STARTUP                     1001
#define IDC_SHUTDOWN                    1002
#define IDC_CANCELPRINT                 1003
#define IDC_STORE                       1004
#define IDC_BEEP                        1004
#define IDC_WORKSTATUS                  1005
#define IDC_CNTPASINK                   1005
#define IDC_DISCNTPASINK                1006
#define IDC_RADIO_XA                    1007
#define IDC_RADIO_SC                    1008
#define IDC_EDIT_PASINK                 1009
#define IDC_BUTTON_BURN                 1010
#define IDC_BUTTON_INIT                 1011
#define IDC_PING                        1011
#define IDC_RADIO_PRINT                 1012
#define IDC_BUTTON_UNINIT               1012
#define IDC_RADIO_TRANSFER              1013
#define IDC_RADIO_BURNER                1014
#define IDC_AREA                        1015
#define IDC_RADIO_CD                    1016
#define IDC_RADIO_PAGENERAL             1016
#define IDC_RADIO_DVD                   1017
#define IDC_RADIO_PATIENTADMIN          1017
#define IDC_COMBO_DEVICE                1021
#define IDC_BUTTON_ERASE                1022
#define IDC_EDIT_DISCNAME               1023
#define IDC_BUTTON_PAUSE                1024
#define IDC_BUTTON_ABORT                1025
#define IDC_COMBO_BURNSPEED             1026
#define IDC_BUTTON_ADD_FILES            1028
#define IDC_BUTTON_ADD_DIRS             1029
#define IDC_LIST_DIR_FILE               1031
#define IDC_EDIT_MSG                    1032
#define IDC_PROGRESS                    1033
#define IDC_BUTTON_PRINT                1035
#define IDC_BUTTON_CANCELPRINT          1036
#define IDC_BUTTON_SETIMAGETYPE         1037
#define IDC_BUTTON_GET_PRINT_SUBMODULE_STATE 1038
#define IDC_BUTTON_DELETE               1039
#define IDC_STATIC_BURN_PHASE           1040
#define IDC_LIST_JOBLIST                1042
#define IDC_BUTTON_DELJOB               1043
#define IDC_COMBO_SVRLIST               1044
#define IDC_EDIT_SERVERAE               1045
#define IDC_EDIT_HOSTAE                 1046
#define IDC_EDIT_SERVERPORT             1047
#define IDC_EDIT_SERVERIP               1048
#define IDC_BUTTON_TRANSFER             1049
#define IDC_BUTTON_TRANSFERBYUID        1050
#define IDC_BUTTON_TRANSFERBYUID_MULTI_SVRS 1051
#define IDC_COMBO_NETWORKNODE           1054
#define IDC_COMBO_FILESELECTION         1059
#define IDC_EDIT_PATIENTNAME            1060
#define IDC_LIST_JOB_QUEUE              1061
#define IDC_BUTTON_CANCEL_JOB           1062
#define IDC_BUTTON_DELET_JOB            1063
#define IDC_BUTTON_MOVE_JOB_UP          1064
#define IDC_BUTTON_SETTINGS             1065
#define IDC_BUTTON_MOVE_JOB_DOWN        1065
#define IDC_BUTTON_VIEW                 1066
#define IDC_BUTTON_HISTORYJOB_COUNT     1066
#define IDC_BUTTON_SHOW_FC              1067
#define IDC_BUTTON_HISTORYJOB_GET_JOB   1067
#define IDC_BUTTON_HISTORYJOB_GET_JOB2  1068
#define IDC_COMBO_PRINT_FILES           1069
#define IDC_BUTTON_HISTORYJOB_GET_JOB3  1069
#define IDC_STATIC_IMAGE_NUM            1070
#define IDC_BUTTON_DELETE_JOB           1072
#define IDC_BUTTON_HIDE_FC              1073
#define IDC_COMBO_IMAGESELECTION        1074
#define IDC_BUTTON_REFRESH_JOB          1074
#define IDC_COMBO_DOWNSCALE             1076
#define IDC_COMBO_UID_SELECTION         1077
#define IDC_EDIT_TRANSFER_UID           1078
#define IDC_BUTTON_FCLOADIMG            1079
#define IDC_COMBO_UID_AUTOSEND_TYPE     1079
#define IDC_EDIT_FCPATH                 1080
#define IDC_BUTTON_FCPATH               1081
#define FC                              1082
#define IDC_BUTTON_STARTFC              1083
#define IDC_COMBO1                      1091
#define IDC_COMBO_SPSSTARTDATE          1091
#define IDC_COMBO_HIS_JOB_PAGES         1091
#define IDC_LIST_PATIENTS               1092
#define IDC_COMBO2                      1092
#define IDC_LIST_STUDY                  1093
#define IDC_EDIT1                       1093
#define IDC_EDIT_STUDYUID               1093
#define IDC_EDIT_CURRENT_NUM            1093
#define IDC_EDIT_SERVER_CALLEDAE        1093
#define IDC_EDIT_AUTOSEND_STUDYUID      1093
#define IDC_EDIT_SEND_JOB_DETAIL_STATE  1093
#define IDC_EDIT_BURN_JOB_DETAIL_STATE  1093
#define IDC_LIST_SERIES                 1094
#define IDC_EDIT2                       1094
#define IDC_EDIT_IMAGE_WIDTH            1094
#define IDC_EDIT_SERVER_PORT            1094
#define IDC_EDIT_SEND_JOB_DETAIL_PHASE  1094
#define IDC_EDIT_BURN_JOB_DETAIL_PHASE  1094
#define IDC_EDIT_PRINT_UID              1094
#define IDC_EDIT_IS_SETTING_P_OR_S_MPPS_INPUT_UID 1094
#define IDC_EDIT_SERVER_CALLINGAE       1095
#define IDC_EDIT_SEND_JOB_DETAIL_PROGRESS 1095
#define IDC_EDIT_BURN_JOB_DETAIL_PROGRESS 1095
#define IDC_LIST_IMAGE                  1095
#define IDC_COMBO_HIS_JOB_COUNT_PER_PAGE 1095
#define IDC_EDIT_IMAGE_HEIGHT           1096
#define IDC_COMBO4                      1097
#define IDC_BUTTON1                     1098
#define IDC_BUTTON_GET_WORKLIST         1098
#define IDC_BUTTON_UPDATE_PATIENTS      1098
#define IDC_BUTTON_L_DCM                1098
#define IDC_BUTTON_REFRESH_DEVICE_MEDIA_INFO 1098
#define IDC_BUTTON_CONIFG_AUTO_ADD      1098
#define IDC_BUTTON_SERVER_OK            1098
#define IDC_BUTTON_TRANSFER_TRANSFER_VALID 1098
#define IDC_BUTTON_IMPORT_JOB_DETAIL_CLOSE 1098
#define IDC_BUTTON_BURN_JOB_DETAIL_CLOSE 1098
#define IDC_BUTTON_SEND_JOB_DETAIL_CLOSE 1098
#define IDC_BUTTON_PAGENERAL_PING       1098
#define IDC_BUTTON2                     1099
#define IDC_BUTTON_SET_MPPS             1099
#define IDC_BUTTON_SET_CRT_STUDY        1099
#define IDC_BUTTON_L_DCMDIR             1099
#define IDC_BUTTON_FIRST                1099
#define IDC_BUTTON_CONIFG_AUTO_MODIFY   1099
#define IDC_BUTTON_SERVER_CANCEL        1099
#define IDC_BUTTON_TRANSFER_AUTOSEND    1099
#define IDC_BUTTON_CLEAR_UID            1099
#define IDC_BUTTON_PRINT_UID_ADD        1099
#define IDC_BUTTON_COMPACT_DB           1099
#define IDC_CHECK1                      1100
#define IDC_BUTTON_GET_PSSTRUCT         1100
#define IDC_BUTTON_SET_CRT_PATIENT      1100
#define IDC_BUTTON_LAST                 1100
#define IDC_BUTTON_CONIFG_AUTO_DELETE   1100
#define IDC_CHECK_SERVER_RAW            1100
#define IDC_CHECK_BURN_DICOM_RAW        1100
#define IDC_CHECK_SEND_AUT_RAW          1100
#define IDC_BUTTON_PRINT_UID_DEL        1100
#define IDC_CHECK2                      1101
#define IDC_CHECK_DICOM                 1101
#define IDC_BUTTON_ISIMPORTED           1101
#define IDC_BUTTON_SET_CRT_SERIES       1101
#define IDC_BUTTON_PREVIOUS             1101
#define IDC_BUTTON_CONIFG_AUTO_SAVE     1101
#define IDC_CHECK_SERVER_PROCESSED      1101
#define IDC_CHECK_SEND_AUT_PRO          1101
#define IDC_BUTTON_PRINT_UID_CLEAR      1101
#define IDC_BUTTON_COMPACT_DATABASE     1101
#define IDC_CHECK3                      1102
#define IDC_BUTTON_SET_MPPS_TEST        1102
#define IDC_BUTTON_DELETE_FROM_DB       1102
#define IDC_BUTTON_NEXT                 1102
#define IDC_BUTTON_CONIFG_AUTO_REFRESH  1102
#define IDC_CHECK_BURN_DICOM_PROC       1102
#define IDC_CHECK_SEND_SVR_RAW          1102
#define IDC_CHECK_BMP                   1103
#define IDC_BUTTON_IS_SET_ENABLE        1103
#define IDC_BUTTON_VIEW_IMAGE           1103
#define IDC_BUTTON_CONIFG_AUTO_CLEAR    1103
#define IDC_CHECK_SEND_SVR_PRO          1103
#define IDC_CHECK_JPEG                  1104
#define IDC_BUTTON_ISWLWORKING          1104
#define IDC_BUTTON_HIDE                 1104
#define IDC_BUTTON_CONIFG_AUTO_TEST     1104
#define IDC_EDIT_ESTIMATEDSIZE          1105
#define IDC_BUTTON_ISMPPSWORKING        1105
#define IDC_EDIT_DISC_CAPACITY          1106
#define IDC_BUTTON_IS_CLOSING_STUDY_MPPS 1106
#define IDC_COMBO_UID_TYPE              1107
#define IDC_BUTTON_ISMPPSVALID          1107
#define IDC_EDIT_DISC_TYPE              1108
#define IDC_BUTTON_IS_CLOSING_PATIENT_OR_STUDY_MPPS 1108
#define IDC_LIST_UIDLIST                1109
#define IDC_BUTTON_STUDY_IMPORTED       1109
#define IDC_EDIT_UID                    1110
#define IDC_BUTTON_IS_STUDYINSTUID_EXIST 1110
#define IDC_BUTTON_DEL_UID              1111
#define IDC_BUTTON_DELETE_ALL_STUDYINSTUID 1111
#define IDC_BUTTON_BURNBYPA             1112
#define IDC_BUTTON_ADD_UID              1113
#define IDC_BUTTON_PSS_OCCUPY_STATE     1114
#define IDC_BUTTON_BURN_UNFINISHEDJOB   1114
#define IDC_BUTTON_CANCEL_FC_PRINT      1115
#define IDC_EDIT_EMPTY_MEDIA            1115
#define IDC_BUTTON_SOCKET_CNCT          1116
#define IDC_BUTTON_SOCKET_SVR           1117
#define IDC_BUTTON_CLOSE_SOCKET_SVR     1118
#define IDC_BUTTON_SOCKET_DISCNCT2      1119
#define IDC_EDIT_CMD_TO_FC              1120
#define IDC_BUTTON_CLEAR                1121
#define IDC_BUTTON_HIDEPROGRESS         1122
#define IDC_BUTTON_SHOWPROGRESS         1123
#define IDC_BUTTON_CHECKDEVICE          1124
#define IDC_BUTTON_UNCHECKDEVICE        1125
#define IDC_BUTTON_LOAD_IN_DIR          1126
#define IDC_EDIT_DCM_EXTENT             1127
#define IDC_BUTTON_BURNPREPARE          1128
#define IDC_BUTTON_CANCELBURNPREPARE    1129
#define IDC_LIST_BURN_PATIENT           1129
#define IDC_STATIC_BURN_INFO_TYPE       1130
#define IDC_BUTTON_LOAD_DCM_IMAGE       1133
#define IDC_BUTTON_SAVE_RAW_IMAGE       1134
#define IDC_RADIO_DCM_READ              1135
#define IDC_BUTTON_LOAD_DCMDIR          1135
#define IDC_BUTTON_VIEW_TAG             1136
#define IDC_BUTTON_VIEW_PATIENT_INFO    1137
#define IDC_LIST_VIEW_DCM_INFO          1138
#define IDC_BUTTON_IMPORT               1139
#define IDC_BUTTON_SEARCH               1140
#define IDC_BUTTON_WLMPPS               1140
#define IDC_EDIT_SEARCH                 1141
#define IDC_BUTTON_CONFIG               1141
#define IDC_BUTTON_DISC_IMPORT          1142
#define IDC_LIST_JOB_LIST               1143
#define IDC_LIST_PATIENT                1144
#define IDC_BUTTON_DISC_IMPORT_UNFINISHEDJOB 1144
#define IDC_BUTTON_REFRESH              1147
#define IDC_BUTTON_CLOSE                1148
#define IDC_COMBO_IMPORT_DEVICE         1149
#define IDC_LIST_IMPORT_SERIES          1151
#define IDC_BUTTON_DI_CANCELJOB         1152
#define IDC_BUTTON_DI_DELETEJOB         1153
#define IDC_BUTTON_TOPMOST              1153
#define IDC_BUTTON_DI_VIEWJOBINFO       1154
#define IDC_BUTTON_TOPMOST2             1154
#define IDC_BUTTON_UID_OCCUPIED         1154
#define IDC_BUTTON_EXIT                 1154
#define IDC_BUTTON_TOPMOST3             1155
#define IDC_BUTTON_SHOW_DESKTOP         1155
#define IDC_COMBO_UG_PRIOR              1155
#define IDC_BUTTON_TOPMOST4             1157
#define IDC_BUTTON_SEND_UG              1157
#define IDC_BUTTON_GEN_REG_FILE         1157
#define IDC_BUTTON_TOPMOST5             1158
#define IDC_COMBO_UG_TYPE               1158
#define IDC_EDIT_UG_ID                  1159
#define IDC_CHECK_UG_BACTIVE            1160
#define IDC_EDIT_GET_DI_STATE           1161
#define IDC_STATIC_JOB_QUEUE            1162
#define IDC_COMBO_BURN_TYPE             1163
#define IDC_STATIC_DATE_TIME            1166
#define IDC_LIST_WORKLIST               1170
#define IDC_LIST_PATIENTSTUDY           1171
#define IDC_STATIC_PSStruct             1172
#define IDC_RADIO_INPROGRESS            1173
#define IDC_RADIO_COMPLETED             1174
#define IDC_RADIO_DISCONTINUED          1175
#define IDC_EDIT_FLAG_IMAGE_INDEX       1175
#define IDC_BUTTON_FLAG_IMAGE           1176
#define IDC_BUTTON_FLAG_ALL_IMAGE       1177
#define IDC_BUTTON_UNFLAG_ALL_IMAGE     1178
#define IDC_BUTTON_CLEAR_FLAG           1179
#define IDC_EDIT_CRT_PATIENT_UID        1180
#define IDC_EDIT_CRT_STUDY_UID          1181
#define IDC_EDIT_CRT_SERIES_UID         1182
#define IDC_BUTTON_FLAGGED_IMAGE_NUM    1183
#define IDC_BUTTON_UNFLAG_IMAGE         1184
#define IDC_EDIT_FLAGGED_IMAGES_NUM     1185
#define IDC_BUTTON_CURRENT_UID          1186
#define IDC_BUTTON_COPY_UID             1187
#define IDC_EDIT_SELECTED_ITEM_UID      1188
#define IDC_BUTTON_CANCEL_L             1189
#define IDC_SLIDER_IMAGE                1191
#define IDC_SLIDER_PLAY_SPEED           1192
#define IDC_CHECK_PLAY                  1193
#define IDC_CHECK_FORWARD               1194
#define IDC_CHECK_REVERSE               1195
#define IDC_CHECK_CYCLE                 1196
#define IDC_STATIC_PLAY_SPEED           1197
#define IDC_BUTTON_SET_IMAGE_SIZE       1198
#define IDC_RADIO_RAW_IMAGE             1200
#define IDC_RADIO_POST_IMAGE            1201
#define IDC_LIST_CONFIG_SEND_AUTO       1201
#define IDC_IPADDRESS_SERVER_IP         1202
#define IDC_RADIO_CONFIG_AUTO_SEND      1203
#define IDC_RADIO_CONFIG_MANUAL_SEND    1204
#define IDC_RADIO_CONFIG_WL             1205
#define IDC_RADIO_CONFIG_MPPS           1206
#define IDC_STATIC_CONFIG_INFO          1207
#define IDC_BUTTON_TRANSFER_REFRESH_NETWORKNODES 1210
#define IDC_LIST_IMPORT_JOB_DETAIL      1212
#define IDC_LIST_SEND_JOB_DETAIL_PSSI   1213
#define IDC_LIST_SEND_JOB_DETAIL_NODES  1214
#define IDC_LIST_BURN_JOB_DETAIL_PSSI   1214
#define IDC_LIST_SEND_JOB_DETAIL_DETAIL 1215
#define IDC_LIST_BURN_JOB_DETAIL_DETAIL 1215
#define IDC_LIST_SEND_MANUAL_UID_LIST   1215
#define IDC_BUTTON_SEND_UID_ADD         1217
#define IDC_BUTTON_SEND_UID_DEL         1218
#define IDC_BUTTON_SEND_UID_CLEAR       1219
#define IDC_LIST_PRINT_UID              1219
#define IDC_BUTTON_DCM_MODIFY           1220
#define IDC_BUTTON_GEN_DCMDIR           1221
#define IDC_LIST_IS_SETTING_P_OR_S_MPPS_PATIENT_UIDS 1222
#define IDC_BUTTON_IS_SETTING_P_OR_S_MPPS_UID_ADD 1223
#define IDC_BUTTON_IS_SETTING_P_OR_S_MPPS_UID_DELETE 1224
#define IDC_BUTTON_IS_SETTING_P_OR_S_MPPS_UID_CLEAR 1225
#define IDC_RADIO_IS_SETTING_P_OR_S_MPPS_PATIENT 1226
#define IDC_RADIO_IS_SETTING_P_OR_S_MPPS_STUDY 1227
#define IDC_EDIT_HIS_JOB_COUNT          1228
#define IDC_EDIT_HIS_JOB_START          1229
#define IDC_EDIT_HIS_JOB_END            1230
#define IDC_LIST_MANUAL_SEND_SERVER     1231
#define ID_TRAY_ABOUT                   32771
#define ID_TRAY_EXIT_UNSD_PA            32772
#define ID_TRAY_ORIGINAL                32774
#define ID_TRAY_EXIT_SD_PA              32776
#define ID_TRAY_SHOW_DESKTOP            32779
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define ID_BUTTON32782                  32782
#define ID_BUTTON32783                  32783
#define ID_BUTTON32784                  32784
#define ID_BUTTON32785                  32785
#define ID_BUTTON32786                  32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON32788                  32788
#define ID_BUTTON32789                  32789
#define ID_BUTTON32790                  32790
#define ID_BUTTON32791                  32791
#define ID_BUTTON32792                  32792
#define ID_BUTTON32793                  32793
#define ID_BUTTON32794                  32794
#define ID_BUTTON32795                  32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1232
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
